#///////////////////////////////////////////////////////////////////////////////
#' Parameter sweep over:
#'  - top n=5 most connected counties within a state
#'  - 4 states + DC = 125 county sets
#'  - R0 from 0.5 to 5 by 0.5 = 10 R0
#'  - initial infected of 1, 10, 100, 1000 equal value per county
#' Results in 5,000 total templates and *100 = 500,000 simulations
#'  => too many to create unique/informative labels
#' Hash and batch IDs are generated by the simulator from GENERATE tokens
#' Metadata tags are passed through to executed metadata but ignored by scenario hash
#' Emily Javan, 02/23/26, TACC
#///////////////////////////////////////////////////////////////////////////////

#///////////////////////////////////////////////////////////////////////////////
#### Load libraries & helper funs ####
library(tidyverse)
library(jsonlite)
source("../data/private_input_data/api_keys.R")
source("helper_funs.R")

#///////////////////////////////////////////////////////////////////////////////
# Set initial conditions
states = c("District-of-Columbia", "New-Jersey", "North-Dakota", "Wisconsin", "North-Carolina")
R0 = seq(0.5, 5, 0.5)
init_inf = c(1, 10, 100, 1000)
simulation_days = 500

metadata_tags = list(
  creator   = "Emily Javan",
  disease   = c("influenza", "flu"),
  sim_day_0 = NULL,
  notes     = c(
    "surrogate model training",
    "R0 sweep",
    "Init exposed sweep",
    "top county sweep"
  )
)

#///////////////////////////////////////////////////////////////////////////////
#### Most connected counties ####
# This ranks the population flowing out of each node per day
# DC is a single node and has no outflow
county_rank_files = list.files(path = paste0("../data/", states), 
                               pattern="_quarterly-2019_county-connection-ranking.csv$", 
                               recursive = T, full.names = T) # 4

# Get only the county row with the highest outflow of people
top_n_counties = map_dfr(
  county_rank_files,
  ~ read_csv(.x, col_types = cols(.default = "c")) %>%
    rename(COUNTY_POP_ACS2023 = POP_ACS2023) %>%
    dplyr::filter(quarter=="4") %>%
    mutate( # needs to be numeric before ranking correctly
      prop_county_outflow       = as.numeric(prop_county_outflow),
      total_pop_outflow         = as.numeric(total_pop_outflow),
      total_counties_connected  = as.numeric(total_counties_connected),
      COUNTY_POP_ACS2023        = as.numeric(COUNTY_POP_ACS2023)
    ) %>%
    arrange(desc(total_pop_outflow), desc(total_counties_connected), desc(COUNTY_POP_ACS2023)) %>%
    slice(1:5)) %>%
  # Adding DC back in manually
  bind_rows(data.frame(
    state_fips = "11",
    state_name = "District-of-Columbia",
    state_abbr = "DC",
    geoid_o = "11001",
    prop_county_outflow = 0,
    total_counties_connected = 0,
    total_pop_outflow = 0)) 

# Counties per state as a named list: state_name -> character vector of geoid_o
counties_by_state = top_n_counties %>%
  dplyr::select(state_name, geoid_o) %>%
  group_by(state_name) %>%
  summarise(counties = list(geoid_o), .groups = "drop") %>%
  tibble::deframe()  # named list: state_name -> county vector

# All subsets of counties (size 1 through n) for each state
county_combos = map_dfr(names(counties_by_state), function(state) {
  counties = counties_by_state[[state]]
  map_dfr(seq_along(counties), function(k) {
    combos = combn(counties, k, simplify = FALSE)
    tibble(state_name = state, county_set = combos)
  })
})

# All unique combinations of county_set x init_inf x R0 = 5000
sweep_combos = crossing(
  county_combos,
  init_inf = init_inf,
  R0       = R0
)

# double checking the county sets look correct and they do: 125 as expected
check_county_combos = sweep_combos %>%
  dplyr::select(county_set) %>%
  distinct()

#///////////////////////////////////////////////////////////////////////////////
#### Create input files ####
# Get base template path
input_dir_path   = "../data/INPUT_FILE_TEMPLATES"
base_file = list.files(path        = input_dir_path,
                       pattern     = "^INPUT_SEIRS-STOCH_BASELINE\\.json$",
                       full.names  = TRUE, recursive  = TRUE)
base_template = jsonlite::fromJSON(base_file, simplifyVector = FALSE)

# Create dir for all initial condition files
commands_dir = "../SEIR-STOCH_Param_Sweep/"
input_scenario_dir = "input_files/"
input_scenario_dir_path = paste0(commands_dir, input_scenario_dir)
dir.create(input_scenario_dir_path, recursive = TRUE)

# Build one template per (county set x init_inf x R0) combo, 
# with initial_infected the same infected value for all in set
scenario_results = pmap(sweep_combos, function(state_name, county_set, init_inf, R0) {
  tmpl <- base_template
  tmpl$initial_infected <- lapply(
    county_set,
    function(county) {
      list(
        county    = county,
        infected  = as.character(init_inf),
        age_group = "2"
      )})
  # Set R0 in disease model
  tmpl$disease_model$parameters$R0 <- as.character(R0)
  
  # Replace STATE tokens, but let the simulator generate output path/hash and batch UUID
  tmpl <- replace_STATE_tokens(tmpl, state_name)
  tmpl$output_dir_path <- "GENERATE"
  tmpl$batch_num <- "GENERATE"
  tmpl$metadata_tags <- metadata_tags
  
  county_label <- paste(county_set, collapse = "-")
  r0_label <- gsub("\\.", "p", as.character(R0))
  scenario_label <- paste0(
    state_name,
    "_counties-", county_label,
    "_init-", init_inf,
    "_R0-", r0_label
  )
  output_path <- paste0(input_scenario_dir, scenario_label, ".json")
  full_output_path <- paste0(input_scenario_dir_path, scenario_label, ".json")
  
  jsonlite::write_json(tmpl, full_output_path,
                       auto_unbox = TRUE, pretty = TRUE, null = "null")
  
  return(list(template = tmpl, scenario_label = scenario_label, output_path = output_path))
})

# Pull templates and add input file paths to sweep_combos for easy inspection
scenario_templates = map(scenario_results, "template")
sweep_combos_final = sweep_combos %>%
  mutate(
    scenario_label = map_chr(scenario_results, "scenario_label"),
    output_path    = map_chr(scenario_results, "output_path")
  )

# Save input metadata for the parameter sweep. Scenario hash and batch are generated by simulator.
sweep_combos_final %>%
  mutate(county_set = map_chr(county_set, paste, collapse = ",")) %>%
  write.table(paste0(commands_dir, "scenario_metadata.txt"),
              sep = "\t", row.names = FALSE, quote = FALSE)

#//////////////////////////////////////
#### Create parallel commands file ####
commands_script_by_state <- sweep_combos_final %>%
  mutate(
    poetry_command_start = paste(
      "poetry run python3 ../src/simulator.py -l INFO -d",
      simulation_days,
      "-i"
    ),
    final_poetry_command = paste(poetry_command_start, output_path)
  ) %>%
  dplyr::select(state_name, final_poetry_command)

commands_script_by_state %>%
  group_by(state_name) %>%
  group_walk(~ {
    state_name <- .y$state_name
    
    write.table(
      .x %>% dplyr::select(final_poetry_command),
      file = paste0(commands_dir, state_name, "_commands.txt"),
      sep = "",
      col.names = FALSE,
      row.names = FALSE,
      quote = FALSE
    )
  })

#//////////////////////////////////////
#### Create parallel launcher file ####
# Read base launcher script
launcher_template <- readLines(paste0(commands_dir, "state_launcher.sh"))
unique_states <- unique(sweep_combos_final$state_name)
for (state in unique_states) {
  new_lines <- launcher_template %>%
    str_replace("MultiCountySweep", paste0(state, "_MultiCountySweep")) %>%
    str_replace_all("state_commands.txt", paste0(state, "_commands.txt"))
  
  # write new launcher script
  writeLines(
    new_lines,
    file.path(commands_dir, paste0(state, "_launcher.sh"))
  )
}






